### ISSUE TITLE
Анализ игроков, за которыми ты наблюдал, пока был в наблюдателях/мёртв? (на Своей демке)

### ISSUE THREAD

**Issue by xBioDreadx** [UnrealKaraulov/UnrealDemoScanner#1]
Есть ли возможность анализировать игроков, за которыми ты наблюдал, пока был в наблюдателях/мёртв? (на Своей демке)
Не всегда есть доступ к чужим демкам, но очень интересно проверить спорные моменты других игроков, за которыми наблюдаешь.

**Comment by UnrealKaraulov** [comment]
Не, все необходимые данные хранятся у игрока.

**Comment by UnrealKaraulov** [comment]
По этому на фасткапе отключили запись демок, что бы защитить своих читеров от сканера.

**Comment by Poluatorul** [comment]
> По этому на фасткапе отключили запись демок, что бы защитить своих читеров от сканера.

Если там отключили демки, то как они смотрят повторы игр и находят читеров? А можно поподробней очень заинтересовали.

**Comment by UnrealKaraulov** [comment]
> > По этому на фасткапе отключили запись демок, что бы защитить своих читеров от сканера.
> 
> Если там отключили демки, то как они смотрят повторы игр и находят читеров? А можно поподробней очень заинтересовали.

Античит не смотрит повторы, он коллекционирует скрины, загруженные модули, запущенные процессы, и прямые изменения в памяти, потом вручную или автоматически приходит бан.

Но доверенные люди вполне могут играть с читами за определенную плату. Раньше этих читеров можно было найти проверив демо, теперь на фасткапе отключена запись демо файлов, и их читеров теперь не вычислить простому игроку.

**Comment by UnrealKaraulov** [comment]
Хотя на фасткапе не играю, но прошел слух что они отключили запись POV демок(хранят огромное количество данных о игроке) а оставили только HLTV (хранит поверхностные данные о всех игроках, но много минусов таких как отсутствие важных данных, иногда сильно ломающих возможность просмотра игры)

**Comment by UnrealKaraulov** [comment]
В принципе можно было бы попробовать использовать данные из HTLV но вряд ли там будет что то полезное
