### ISSUE TITLE
Detected Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by Ganji89420** [UnrealKaraulov/UnrealDemoScanner#11]
![Capture](https://github.com/UnrealKaraulov/UnrealDemoScanner/assets/151049632/5775da98-3d01-479f-9dca-34c7b4611044)

I've been downloading your updates for quite some time now (maybe a year?) and never had any issues. But the newest update 1.72.10b is coming back blocked on my system with a positive trojan detection. I tried the download multiple times. Came back the same each time.

Im currently using Beta 1.72.9b

**Comment by thcporfavor** [comment]
Malwarebytes has also marked the revoicedecoder as malware.

**Comment by UnrealKaraulov** [comment]
@Ganji89420 @thcporfavor 

Thanks for report, if possible please send files to malwarebytes/microsoft av report email. 

I can try fix false detects in next update.
