### ISSUE TITLE
Probability of false positives?

### ISSUE THREAD

**Issue by randomwalker42** [UnrealKaraulov/UnrealDemoScanner#12]
Hi, many thanks to you for providing such a tool! 

I've been using this for quite a long time, and my impression is that it's got high precision (when it caught something it's usually correct), but low recall (still many cheaters got away with it). So when the scanner caught a case, I tend to be confident about it. 

Recently, one demo was scanned and showed more than 20 lines of aim types with different weapons, from the start to the end of the demo. From my own experience, I'm confident that this is cheating but the guy insisted his innocence. Since I didn't really read the source code, I want to ask about whether it's indeed possible for this case to be a false positive? 

Although I seriously doubt this, would some specific user config setting or change of weapon/skin/player lead to such a result? Or any specific pattern of moving the mouse that could trigger the scanner? 

Would like to hear if you have similar experiences, thanks in advance.

**Comment by UnrealKaraulov** [comment]
@randomwalker42 You can share demo file or scan results screenshot ?
