### ISSUE TITLE
Detecting aim with no modifications

### ISSUE THREAD

**Issue by TheManuka** [UnrealKaraulov/UnrealDemoScanner#14]
Hi there. I've been trying to understand how we can help players fix their CS 1.6 when being banned for aim while claiming they don't have modifications.

I've been banned for aim in my own server while playing on Steam account with no modifications. I've uninstalled CS,  deleted all CS related files and reinstalled from the Steam library only to keep having /aim hit me up and ban me again.

I have noticed that when I downgrade my CS resolution to not HD, I never show up on /aim. But as soon as I try upscaling my resolution.. there I go back into the detector.

Is there a recommended resolution for players to use while playing to not be falsely detected or any way for a player to pinpoint the issue and remove whatever makes a posible false positive? Does unreal provide a way to pinpoint the issue on the client side? Maybe a bad dll to be removed.

Thanks!

**Comment by UnrealKaraulov** [comment]
Screenshots ?
Demo file ?

**Comment by TheManuka** [comment]
I just deleted my Steam CS, reinstalled and recorded two consecutive demos in GunGame mode.
During both demo's I'm constantly type /aim (binded of course).

[Demo link](https://1drv.ms/f/s!Aly4VE4ltromgpJctu2aSLvBYlXhhA?e=KP5IVy)


In SD I never come up (but scan reveals an Aim type 7.2 weapon_mp5n warning):

![Gungame SD Fullscreen result](https://github.com/user-attachments/assets/8f1976f2-24a2-4865-8d51-107cdaf2a38e)

---

In HD I appear a couple of times (I think up to 2 but have seen it as high as 4 or banned) and an Aim type 5.5 weapon_tmp and aim type 7.3 weapon hegranade warning shows up.

![Gungame HD windowed result](https://github.com/user-attachments/assets/fe0d0810-e18b-4466-aaae-78e475dcb336)



`I'm willing to open my CS and screenshare anything that is needed with the hopes of understanding or in hopes of finding a solution.`

**Comment by UnrealKaraulov** [comment]
Nothing detected in this screenshots. Please read manuals from 8 and 11 commands after scan. 

### warnings **≠** detects
