### ISSUE TITLE
release-fles:  version-string

### ISSUE THREAD

**Issue by fred0r** [UnrealKaraulov/UnrealDemoScanner#2]
would be nice if the files downloaded from the 'releases-page' contain its version number

**Comment by UnrealKaraulov** [comment]
@fred0r sorry I can't fix this fatal issue :(

**Comment by fred0r** [comment]
ofc its not fatal..... thanks for your work.

**Comment by UnrealKaraulov** [comment]
@fred0r if you found demos with false detects please create new issue, thanks
