### ISSUE TITLE
Error at the end of demo analysis

### ISSUE THREAD

**Issue by NiceFeatures** [UnrealKaraulov/UnrealDemoScanner#3]
[PLUGIN] AMXX Plugin not found. Some detects is skipped.

**Comment by UnrealKaraulov** [comment]
Where you see error ?

**Comment by UnrealKaraulov** [comment]
This message written in any demos without plugin. (Plugin can be found here : https://github.com/UnrealKaraulov/UnrealDemoScanner/tree/main/PLUGIN )
