### ISSUE TITLE
Load more than one Demo -in one execution-

### ISSUE THREAD

**Issue by RauliTop** [UnrealKaraulov/UnrealDemoScanner#4]
You drag one Demo and scan completed ok.

But when you drag another Demo, can't be scanned.
Program must close and open again to scan more than 1 Demo.

Anyways, good job with this. Continue developing it!!

**Comment by UnrealKaraulov** [comment]
@RauliTop main class in my scanner is static and hard to cleanup all vars after first demo.

**Comment by UnrealKaraulov** [comment]
you can drop every demo in executable or using batch script
