### ISSUE TITLE
unreal demo scanner 2

### ISSUE THREAD

**Issue by Kiber2282** [UnrealKaraulov/UnrealDemoScanner#5]
как добавлять исходный код? 
и как исправить данную ошибку 
[Модуль] Не найден бесплатный серверный модуль. Часть данных недоступна.

**Comment by UnrealKaraulov** [comment]
Эта не ошибка , просто рекомендация https://github.com/UnrealKaraulov/UnrealDemoScanner/tree/v1.65.b8/PLUGIN
