### ISSUE TITLE
Возможность вытаскивать войс со старых демках

### ISSUE THREAD

**Issue by atmega1337** [UnrealKaraulov/UnrealDemoScanner#6]
Если закидывать и вытаскивать войс с демок сделанных на старых версий cs - получаю пустые файлы.
Планируется ли доработка для работы с демками старых версий cs?
![image](https://user-images.githubusercontent.com/14110195/182027357-b9a615f4-085b-4e1e-a389-25372031732c.png)

**Comment by UnrealKaraulov** [comment]
@TofikMarcelo команда 10 после сканирования демки, чат просмотр.

На счет войса, я не смогу сделать т.к не я разработчик revoice и не знаю как его правильно использовать для раскодирования файлов.
