### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TomArrow** [UnrealKaraulov/UnrealDemoScanner#7]
Hi, what license is this code under? Can I use it in a GPL 2.0 tool?

**Comment by UnrealKaraulov** [comment]
@TomArrow I don't know what is the license :(

Which license should I must choose?

**Comment by UnrealKaraulov** [comment]
@TomArrow This tool based at https://github.com/Traderain/VolvoWrench https://github.com/Traderain/VolvoWrench/blob/master/LICENSE

**Comment by TomArrow** [comment]
Ah! WTFPL would be good. Could you add the same license to your code? WTFPL is complete freedom with no restrictions, but there are others too. But not all are compatible with GPL 2 which I need.

**Comment by UnrealKaraulov** [comment]
@TomArrow added license from this project https://github.com/UnrealKaraulov/UnrealDemoScanner/blob/main/LICENSE

**Comment by TomArrow** [comment]
Thanks! Perfect.

**Comment by UnrealKaraulov** [comment]
> Can I use it in a GPL 2.0 tool?

What is tool?

**Comment by TomArrow** [comment]
This one: https://github.com/TomArrow/JK2DemoCutter

I don't know if I will do it yet, but I thought it might be funny to be able to convert CS demos to Jedi Knight or Quake 3 demos.

**Comment by UnrealKaraulov** [comment]
> I don't know if I will do it yet, but I thought it might be funny to be able to convert CS demos to Jedi Knight or Quake 3 demos.

My tool is Hack(/Cheat) Detector, can detect cheats, etc, by patterns.

But demo parser based at https://github.com/Traderain/VolvoWrench code.

**Comment by TomArrow** [comment]
Ah fair
