### ISSUE TITLE
Separate demos in a different branch...

### ISSUE THREAD

**Issue by deprale** [UnrealKaraulov/UnrealDemoScanner#8]
Please for the love of GOD, separate the demos in a different branch.

I wanted to commit something but it's impossible with my internet... 130MB in and I'm not even at 10% of downloading... 

SOURCE CODE -> branch SRC
DEMOS/JUNK THAT NOBODY NEEDS -> branch DEMOS

very simple.

**Comment by UnrealKaraulov** [comment]
@deprale sorry, no.
